// <auto-generated />
using E_Commerce.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240101181347_ProductDB")]
    partial class ProductDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("new_price")
                        .HasColumnType("float");

                    b.Property<double>("old_price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            category = "women",
                            image = "p1_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 50.0,
                            old_price = 80.5
                        },
                        new
                        {
                            id = 2,
                            category = "women",
                            image = "p2_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 3,
                            category = "women",
                            image = "p3_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 60.0,
                            old_price = 100.5
                        },
                        new
                        {
                            id = 4,
                            category = "women",
                            image = "p4_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 100.0,
                            old_price = 150.0
                        },
                        new
                        {
                            id = 5,
                            category = "women",
                            image = "p5_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 6,
                            category = "women",
                            image = "p6_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 7,
                            category = "women",
                            image = "p7_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 8,
                            category = "women",
                            image = "p8_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 9,
                            category = "women",
                            image = "p9_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 10,
                            category = "women",
                            image = "p10_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 11,
                            category = "women",
                            image = "p11_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 12,
                            category = "women",
                            image = "p12_img",
                            name = "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 13,
                            category = "men",
                            image = "p13_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 14,
                            category = "men",
                            image = "p14_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 15,
                            category = "men",
                            image = "p15_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 16,
                            category = "men",
                            image = "p16_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 17,
                            category = "men",
                            image = "p17_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 18,
                            category = "men",
                            image = "p18_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 19,
                            category = "men",
                            image = "p19_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 20,
                            category = "men",
                            image = "p20_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 21,
                            category = "men",
                            image = "p21_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 22,
                            category = "men",
                            image = "p22_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 23,
                            category = "men",
                            image = "p23_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 24,
                            category = "men",
                            image = "p24_img",
                            name = "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 25,
                            category = "kid",
                            image = "p25_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 26,
                            category = "kid",
                            image = "p26_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 27,
                            category = "kid",
                            image = "p27_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 28,
                            category = "kid",
                            image = "p28_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 29,
                            category = "kid",
                            image = "p29_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 30,
                            category = "kid",
                            image = "p30_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 31,
                            category = "kid",
                            image = "p31_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 32,
                            category = "kid",
                            image = "p32_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 33,
                            category = "kid",
                            image = "p33_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 34,
                            category = "kid",
                            image = "p34_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 35,
                            category = "kid",
                            image = "p35_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        },
                        new
                        {
                            id = 36,
                            category = "kid",
                            image = "p36_img",
                            name = "Boys Orange Colourblocked Hooded Sweatshirt",
                            new_price = 85.0,
                            old_price = 120.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
